### ISSUE TITLE
How to add new social link icons

### ISSUE THREAD

**Issue by chaitjo** [sergiokopplin/indigo#271]
Hi there! I love this template and am in the processes of building my portfolio using it. I'm not very familiar with front-end development and was wondering how I could add a custom social link icon (for example, Google Scholar).

**Comment by louisjwilliams** [comment]
I'd be interested in this as well. I'm looking to be able to link to an imdb page.

**Comment by vivekkrish** [comment]
Hi @chaitjo, @louisjwilliams -

In order to add a new/custom social link icon, you would need to follow the steps below (the example is based on adding a link to Google Scholar):
* Add `site: username` entry to [_config.yml](https://github.com/vivekkrish/vivekkrish.github.io/blob/03f3dfe52a9c18604c1baca8533c2192e0a63ef5/_config.yml#L40)
* Add SVG snippet to [icons.html](https://github.com/vivekkrish/vivekkrish.github.io/blob/03f3dfe52a9c18604c1baca8533c2192e0a63ef5/_includes/icons.html#L107-L110)
* Add linkout stanza to [social-links.html](https://github.com/vivekkrish/vivekkrish.github.io/blob/03f3dfe52a9c18604c1baca8533c2192e0a63ef5/_includes/social-links.html#L2-L6)

@louisjwilliams, you can find an SVG version of the IMDB icon from here: https://simpleicons.org/?q=imdb. Download and open the file in a text editor and convert it to look similar to the SVG snippet linked above for Google Scholar.

Hope this helps!

P.S.: In a future version of this theme, adding and configuring social links will become a bit easier, once PR #251 is merged.

**Comment by louisjwilliams** [comment]
Thanks. I appreciate the help.

**Comment by mehmandarov** [comment]
Thanks for your reply, @vivekkrish! 
@chaitjo && @louisjwilliams: Another example of the current way of doing it can be found here: https://github.com/sergiokopplin/indigo/issues/285.
