### ISSUE TITLE
Default Branch not Master

### ISSUE THREAD

**Issue by jamesstonehill** [sergiokopplin/indigo#293]
Why is the default branch for this repo not master?

**Comment by sergiokopplin** [comment]
Github pages has some feature for developer.

A have a main branch on my account and it points to my master.
My website is https://koppl.in and it points to github.com/sergiokopplin/sergiokopplin MASTER BRANCH
Any other repo must have the gh-pages branch to have as subdomain.

For example:
https://koppl.in/example can be github.com/sergiokopplin/example with gh-pages branch.

It will not work if you usa a master branch on subdomains, only on your main repo.

So, that's why i have sergiokopplin/indigo under gh-pages branch.
