### ISSUE TITLE
How do I make my own project?

### ISSUE THREAD

**Issue by OscarGorog** [sergiokopplin/indigo#351]
How do I make my own project. I have all the files installed but cannot seem how to configure my own project except for the default one.

Thanks

**Comment by sylvainmetayer** [comment]
Did you read [the setup](https://github.com/sergiokopplin/indigo#setup) explanation ? Or is their something that went wrong while following it ? It seems that you have already forked the repository, you just have to customize it on your own fork now to make it your.

**Comment by OscarGorog** [comment]
Yes but how do I set up my own project there is no explanation?

Thanks,
Oscar

**Comment by sylvainmetayer** [comment]
On your fork, edit the file _config.yml to edit the title and bio of your site. Then, add files in the post folder to create some post.

**Comment by mehmandarov** [comment]
Most of the things you need to modify is in _config.yaml file at the root of this project.

The rest is generic info on how to run Jekyll projects: 

* General info on configuring Jekyll: https://jekyllrb.com/docs/configuration/
* Info on running Jekyll on GitHub Pages: https://jekyllrb.com/docs/github-pages/

Closing this issue since it is generic question on Jekyll. :)

**Comment by OscarGorog** [comment]
thanks @sylvainmetayer the posts folder is what I needed.

Thanks
