### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by kunalbotla** [sergiokopplin/indigo#434]
What are the differences between each branch? I have made edits to the master branch but don't know what to do to transfer the data to the gh-pages branch to deploy to GitHub Pages.

**Comment by sylvainmetayer** [comment]
Hello,

Master branch contains a github actions yaml file which allow to build and deploy site, with custom extension such as the Font awesome's one. This then deploy the builded site to gh-page branch, which would not be possible directly from gh-page as it was the case before because Github does not allow custom extension / gem (for obvious security issues). 

Basically, their is no difference except this file. However, this *may* be reverted and is still in discussion in #416  about weither or not keep this behaviour.

**Comment by sergiokopplin** [comment]
I've updated. So only gh-pages for now.
